Governance: failure feedback (#542)
### Description

After a little talk with Volpe where he asked why a tx was failing i
thought we could be showing the errors in a better way.

#### Other changes



### Tested

NEW tests!
```
yarn celocli governance:build-proposal --node celo
Transaction #1:
? Celo Contract: FeeCurrencyDirectory
? FeeCurrencyDirectory Function: transferOwnership
? newOwner: 0x2F25deB3848C207fc8E0c34035B3Ba7fC157602B
Error: Couldn't build call for transaction:
 {"contract":"FeeCurrencyDirectory","function":"transferOwnership","args":["0x2F25deB3848C207fc8E0c34035B3Ba7fC157602B"],"value":"0"}
Due to Failures:
 1. FeeCurrencyDirectory not (yet) registered
 2. FeeCurrencyDirectory is not a core celo contract so address must be specified
    at ProposalBuilder.<anonymous> (/Users/aaronderuvo/celo/developer-tooling/packages/sdk/governance/lib/proposal-builder.js:187:19)
    at Generator.throw (<anonymous>)
    at rejected (/Users/aaronderuvo/celo/developer-tooling/packages/sdk/governance/lib/proposal-builder.js:6:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Please retry forming this transaction
Transaction #1:
```

### How to QA
```
yarn celocli governance:build-proposal --node celo
Transaction #1:
? Celo Contract: FeeCurrencyDirectory
? FeeCurrencyDirectory Function: transferOwnership
? newOwner: 0x2F25deB3848C207fc8E0c34035B3Ba7fC157602B
```

note this QA will only work before we move to L2. but for now it is an
easy way to show the error.


### Related issues

- Fixes #[issue number here]

<!-- start pr-codex -->

---

## PR-Codex overview
This PR enhances the error handling in the `ProposalBuilder` class by
providing more informative error messages when building proposals fails.
It also includes new tests to verify this functionality.

### Detailed summary
- Added `isNativeError` import from `util/types`.
- Introduced an `issues` array to collect error messages from failed
strategies.
- Updated the error message thrown when transaction building fails to
include detailed issues.
- Added tests for `fromJsonTx` to check transaction building success and
failure scenarios.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your
question}`

<!-- end pr-codex -->